sonar.projectKey=BoggyBumblebee_quickie
sonar.organization=boggybumblebee
sonar.projectName=Quickie
sonar.sources=Sources
sonar.tests=Tests
sonar.test.inclusions=Tests/**/*.swift
sonar.coverageReportPaths=sonar-generic-coverage.xml
sonar.coverage.exclusions=Sources/AppDelegate.swift,Sources/GlobalHotKeyRegistrar.swift,Sources/QuickieApp.swift,Sources/ReminderFormView.swift,Sources/ReminderService.swift,Sources/SettingsView.swift,Sources/StatusIcon.swift
